"""Accounting domain repository contracts."""

from __future__ import annotations

from datetime import date
from typing import Protocol
from uuid import UUID

from mfm.domain.accounting.account_number import AccountNumber
from mfm.domain.accounting.fiscal_year import FiscalYear
from mfm.domain.accounting.journal import Journal
from mfm.domain.accounting.ledger_account import LedgerAccount


class JournalRepository(Protocol):
    def add(self, journal: Journal) -> None: ...

    def get_by_id(self, journal_id: UUID) -> Journal | None: ...

    def get_by_number(self, *, fiscal_year: int, journal_number: str) -> Journal | None: ...

    def update(self, journal: Journal) -> None: ...

    def list(self) -> list[Journal]: ...

    def list_by_reference(self, reference: str) -> list[Journal]: ...

    def list_by_posting_date_range(self, *, start_date: date, end_date: date) -> list[Journal]: ...


class LedgerAccountRepository(Protocol):
    def add(self, account: LedgerAccount) -> None: ...

    def get_by_id(self, account_id: UUID) -> LedgerAccount | None: ...

    def get_by_number(self, account_number: AccountNumber) -> LedgerAccount | None: ...

    def update(self, account: LedgerAccount) -> None: ...

    def list(self) -> list[LedgerAccount]: ...

    def list_active(self) -> list[LedgerAccount]: ...


class FiscalYearRepository(Protocol):
    def add(self, fiscal_year: FiscalYear) -> None: ...

    def get_by_id(self, fiscal_year_id: UUID) -> FiscalYear | None: ...

    def get_by_year(self, year: int) -> FiscalYear | None: ...

    def get_open(self) -> FiscalYear | None: ...

    def update(self, fiscal_year: FiscalYear) -> None: ...

    def list(self) -> list[FiscalYear]: ...
