"""add membership billing tables

Revision ID: 093ad0868ee4
Revises: ac4e2d6b685f
Create Date: 2026-08-25 07:52:26.648872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093ad0868ee4'
down_revision: Union[str, Sequence[str], None] = 'ac4e2d6b685f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_fee_schedule',
    sa.Column('membership_type_id', sa.Uuid(), nullable=False),
    sa.Column('membership_type_code', sa.String(length=50), nullable=False),
    sa.Column('membership_type_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_days', sa.Integer(), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership_fee_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_fee_schedule_membership_type_id'), ['membership_type_id'], unique=True)

    op.create_table('membership_billing_reminder',
    sa.Column('fee_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fee_schedule_id'], ['membership_fee_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership_billing_reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_billing_reminder_fee_schedule_id'), ['fee_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_billing_reminder_member_id'), ['member_id'], unique=False)

    op.create_table('membership_billing_run',
    sa.Column('fee_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('invoices_created', sa.Integer(), nullable=False),
    sa.Column('journals_created', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fee_schedule_id'], ['membership_fee_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership_billing_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_billing_run_fee_schedule_id'), ['fee_schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_billing_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_billing_run_fee_schedule_id'))

    op.drop_table('membership_billing_run')
    with op.batch_alter_table('membership_billing_reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_billing_reminder_member_id'))
        batch_op.drop_index(batch_op.f('ix_membership_billing_reminder_fee_schedule_id'))

    op.drop_table('membership_billing_reminder')
    with op.batch_alter_table('membership_fee_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_fee_schedule_membership_type_id'))

    op.drop_table('membership_fee_schedule')
    # ### end Alembic commands ###
