"""baseline schema

Revision ID: ac4e2d6b685f
Revises: 
Create Date: 2026-08-25 06:52:03.768060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4e2d6b685f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('asset_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('category', sa.Enum('VESSEL', 'ENGINE', 'EQUIPMENT', 'BUILDING', 'TOOL', 'OTHER', name='assetcategory', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RETIRED', 'DISPOSED', name='assetstatus', native_enum=False, length=20), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('retired_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_asset_number'), ['asset_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_owner_id'), ['owner_id'], unique=False)

    op.create_table('certificate',
    sa.Column('certificate_type_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_type_code', sa.String(length=120), nullable=False),
    sa.Column('certificate_type_display_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('certificate_number', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.Enum('VESSEL', 'ORGANIZATION', name='certificatetargettype', native_enum=False, length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('issuer_type', sa.Enum('AUTHORITY', 'CLASSIFICATION_SOCIETY', 'INSPECTION_BODY', 'OTHER_ORGANIZATION', name='issuerreferencetype', native_enum=False, length=40), nullable=False),
    sa.Column('issuer_id_or_external_key', sa.String(length=255), nullable=False),
    sa.Column('issuer_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'REVOKED', 'EXPIRED', name='certificatestatus', native_enum=False, length=20), nullable=False),
    sa.Column('renewal_required', sa.Boolean(), nullable=False),
    sa.Column('renewed_from_certificate_id', sa.Uuid(), nullable=True),
    sa.Column('document_reference', sa.String(length=1000), nullable=True),
    sa.Column('external_document_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['renewed_from_certificate_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_certificate_type_id'), ['certificate_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_renewed_from_certificate_id'), ['renewed_from_certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_target_id'), ['target_id'], unique=False)

    op.create_table('contact',
    sa.Column('contact_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DELETED', name='contactstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_contact_number'), ['contact_number'], unique=True)

    op.create_table('document',
    sa.Column('document_number', sa.String(length=120), nullable=False),
    sa.Column('document_title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', 'DISPOSED', name='documentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('document_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disposed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_document_number'), ['document_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_document_document_type'), ['document_type'], unique=False)

    op.create_table('fiscal_year',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'ARCHIVED', name='fiscalyearstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fiscal_year', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_year_year'), ['year'], unique=True)

    op.create_table('inventory_item',
    sa.Column('item_reference', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('unit_code', sa.String(length=40), nullable=False),
    sa.Column('unit_decimal_places', sa.Integer(), nullable=False),
    sa.Column('unit_display_name', sa.String(length=120), nullable=True),
    sa.Column('minimum_stock_level', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='inventoryitemstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_item_item_reference'), ['item_reference'], unique=False)

    op.create_table('ledger_account',
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='accounttype', native_enum=False, length=20), nullable=False),
    sa.Column('normal_balance', sa.Enum('DEBIT', 'CREDIT', name='normalbalance', native_enum=False, length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('has_postings', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_account_account_number'), ['account_number'], unique=True)

    op.create_table('maintenance_plan',
    sa.Column('target_type', sa.Enum('VESSEL', 'TECHNICAL_COMPONENT', name='maintenancetargettype', native_enum=False, length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='maintenanceplanstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_plan_target_id'), ['target_id'], unique=False)

    op.create_table('membership_type',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'YOUTH', 'SENIOR', 'FAMILY', 'CORPORATE', name='membershipcategory', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_type_code'), ['code'], unique=True)

    op.create_table('organization',
    sa.Column('organization_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.Enum('ASSOCIATION', 'FOUNDATION', 'COMPANY', 'COMMITTEE', 'OTHER', name='organizationtype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='organizationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_organization_number'), ['organization_number'], unique=True)

    op.create_table('project',
    sa.Column('project_number', sa.String(length=120), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='projectpriority', native_enum=False, length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_project_number'), ['project_number'], unique=True)

    op.create_table('purchase_order',
    sa.Column('purchase_order_number', sa.String(length=120), nullable=False),
    sa.Column('supplier_reference', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'ORDERED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='purchaseorderstatus', native_enum=False, length=40), nullable=False),
    sa.Column('currency', sa.Enum('DKK', 'EUR', 'USD', 'GBP', 'NOK', 'SEK', name='currency', native_enum=False, length=10), nullable=False),
    sa.Column('order_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('supplier_contact_snapshot', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('requested_by_reference', sa.String(length=255), nullable=True),
    sa.Column('approved_by_reference', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_order_reference', sa.String(length=255), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_purchase_order_number'), ['purchase_order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_order_supplier_reference'), ['supplier_reference'], unique=False)

    op.create_table('technical_configuration',
    sa.Column('vessel_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='technicalconfigurationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technical_configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_configuration_vessel_id'), ['vessel_id'], unique=False)

    op.create_table('voyage',
    sa.Column('vessel_id', sa.Uuid(), nullable=False),
    sa.Column('voyage_reference', sa.String(length=255), nullable=True),
    sa.Column('planned_departure_location_external_id', sa.String(length=255), nullable=True),
    sa.Column('planned_departure_location_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('planned_departure_location_locality_snapshot', sa.String(length=255), nullable=True),
    sa.Column('planned_departure_location_country_snapshot', sa.String(length=255), nullable=True),
    sa.Column('planned_arrival_location_external_id', sa.String(length=255), nullable=True),
    sa.Column('planned_arrival_location_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('planned_arrival_location_locality_snapshot', sa.String(length=255), nullable=True),
    sa.Column('planned_arrival_location_country_snapshot', sa.String(length=255), nullable=True),
    sa.Column('planned_departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNED', 'UNDERWAY', 'COMPLETED', 'CANCELLED', name='voyagestatus', native_enum=False, length=20), nullable=False),
    sa.Column('actual_departure_location_external_id', sa.String(length=255), nullable=True),
    sa.Column('actual_departure_location_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('actual_departure_location_locality_snapshot', sa.String(length=255), nullable=True),
    sa.Column('actual_departure_location_country_snapshot', sa.String(length=255), nullable=True),
    sa.Column('actual_arrival_location_external_id', sa.String(length=255), nullable=True),
    sa.Column('actual_arrival_location_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('actual_arrival_location_locality_snapshot', sa.String(length=255), nullable=True),
    sa.Column('actual_arrival_location_country_snapshot', sa.String(length=255), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purpose_code', sa.Enum('OPERATIONAL', 'TRAINING', 'PRESERVATION', 'DEMONSTRATION', 'TRANSFER', 'INSPECTION', 'OTHER', name='voyagepurposecode', native_enum=False, length=40), nullable=True),
    sa.Column('purpose_detail', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=1000), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_reference', sa.String(length=255), nullable=True),
    sa.Column('document_reference', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voyage_vessel_id'), ['vessel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voyage_voyage_reference'), ['voyage_reference'], unique=False)

    op.create_table('work_order',
    sa.Column('maintenance_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.Enum('VESSEL', 'TECHNICAL_COMPONENT', name='maintenancetargettype', native_enum=False, length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='workorderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performer_type', sa.Enum('MEMBER', 'VOLUNTEER', 'EXTERNAL_PERSON', 'EXTERNAL_COMPANY', name='performerreferencetype', native_enum=False, length=40), nullable=True),
    sa.Column('performer_id_or_external_key', sa.String(length=255), nullable=True),
    sa.Column('performer_display_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_maintenance_requirement_id'), ['maintenance_requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_target_id'), ['target_id'], unique=False)

    op.create_table('CONTACT_RELATION',
    sa.Column('RelationID', sa.String(length=36), nullable=False),
    sa.Column('FromContactID', sa.Uuid(), nullable=False),
    sa.Column('ToContactID', sa.Uuid(), nullable=False),
    sa.Column('RelationType', sa.Enum('CONTACT_PERSON', 'MEMBER_OF', 'SUPPLIER', 'SPONSOR', 'DONOR', 'AUTHORITY', 'OTHER', name='relationtype'), nullable=False),
    sa.Column('ValidFrom', sa.Date(), nullable=False),
    sa.Column('ValidTo', sa.Date(), nullable=True),
    sa.Column('IsCurrent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['FromContactID'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['ToContactID'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('RelationID')
    )
    op.create_table('asset_location',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_location_asset_id'), ['asset_id'], unique=True)

    op.create_table('board',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('term_start', sa.Date(), nullable=False),
    sa.Column('term_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'ARCHIVED', name='boardstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_organization_id'), ['organization_id'], unique=False)

    op.create_table('certificate_compliance_observation',
    sa.Column('certificate_id', sa.Uuid(), nullable=False),
    sa.Column('observation_order', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('requires_maintenance_work', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate_compliance_observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_compliance_observation_certificate_id'), ['certificate_id'], unique=False)

    op.create_table('committee',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='committeestatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('committee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_committee_organization_id'), ['organization_id'], unique=False)

    op.create_table('contact_address',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('address_type', sa.Enum('HOME', 'POSTAL', 'WORK', 'OTHER', name='addresstype', native_enum=False, length=20), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_address_contact_id'), ['contact_id'], unique=False)

    op.create_table('contact_email',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.Enum('PRIVATE', 'WORK', 'OTHER', name='emailtype', native_enum=False, length=20), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_email_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_email_contact_id'), ['contact_id'], unique=False)

    op.create_table('contact_organisation',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cvr', sa.String(length=50), nullable=False),
    sa.Column('vat', sa.String(length=50), nullable=False),
    sa.Column('ean', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    op.create_table('contact_person',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id')
    )
    op.create_table('contact_phone',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('phone_type', sa.Enum('MOBILE', 'LANDLINE', 'WORK', 'OTHER', name='phonetype', native_enum=False, length=20), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_phone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_phone_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_phone_number'), ['number'], unique=False)

    op.create_table('contingent_plan',
    sa.Column('membership_type_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('DKK', 'EUR', 'USD', name='currency', native_enum=False, length=10), nullable=False),
    sa.Column('billing_period', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billingperiod', native_enum=False, length=20), nullable=False),
    sa.Column('due_days', sa.Integer(), nullable=False),
    sa.Column('prorate_on_start', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membership_type_id'], ['membership_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contingent_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contingent_plan_membership_type_id'), ['membership_type_id'], unique=False)

    op.create_table('document_reference',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('reference_order', sa.Integer(), nullable=True),
    sa.Column('version_order', sa.Integer(), nullable=True),
    sa.Column('has_version', sa.Boolean(), nullable=False),
    sa.Column('has_reference', sa.Boolean(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('version_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_capability', sa.String(length=80), nullable=True),
    sa.Column('target_aggregate_type', sa.String(length=120), nullable=True),
    sa.Column('target_aggregate_id', sa.String(length=120), nullable=True),
    sa.Column('exists', sa.Boolean(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=True),
    sa.Column('is_soft_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'reference_order', name='uq_document_reference_order'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_reference_version_number'),
    sa.UniqueConstraint('document_id', 'version_order', name='uq_document_reference_version_order')
    )
    with op.batch_alter_table('document_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_reference_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_reference_target_aggregate_id'), ['target_aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_reference_target_capability'), ['target_capability'], unique=False)

    op.create_table('fiscal_period',
    sa.Column('fiscal_year_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year_id', 'number', name='uq_fiscal_period_number_per_year')
    )
    with op.batch_alter_table('fiscal_period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_period_fiscal_year_id'), ['fiscal_year_id'], unique=False)

    op.create_table('inventory_stock_movement',
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('movement_order', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('RECEIPT', 'ISSUE', 'ADJUSTMENT_INCREASE', 'ADJUSTMENT_DECREASE', name='stockmovementtype', native_enum=False, length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_key', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('vessel_id', sa.Uuid(), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id', 'movement_order', name='uq_inventory_stock_movement_item_order')
    )
    with op.batch_alter_table('inventory_stock_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_stock_movement_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_stock_movement_movement_order'), ['movement_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_stock_movement_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('inventory_stock_position',
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('location_key', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('vessel_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id', 'location_key', name='uq_inventory_stock_position_item_location')
    )
    with op.batch_alter_table('inventory_stock_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_stock_position_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_stock_position_location_key'), ['location_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_stock_position_vessel_id'), ['vessel_id'], unique=False)

    op.create_table('journal',
    sa.Column('fiscal_year_id', sa.Uuid(), nullable=False),
    sa.Column('journal_number', sa.String(length=120), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'REVERSED', name='journalentrystatus', native_enum=False, length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_year_id', 'journal_number', name='uq_journal_number_within_fiscal_year')
    )
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_fiscal_year_id'), ['fiscal_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_journal_number'), ['journal_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_posting_date'), ['posting_date'], unique=False)

    op.create_table('maintenance_record',
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.Enum('VESSEL', 'TECHNICAL_COMPONENT', name='maintenancetargettype', native_enum=False, length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performer_type', sa.Enum('MEMBER', 'VOLUNTEER', 'EXTERNAL_PERSON', 'EXTERNAL_COMPANY', name='performerreferencetype', native_enum=False, length=40), nullable=True),
    sa.Column('performer_id_or_external_key', sa.String(length=255), nullable=True),
    sa.Column('performer_display_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('finding', sa.String(length=4000), nullable=True),
    sa.Column('replacement_may_be_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_record_maintenance_requirement_id'), ['maintenance_requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_record_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_record_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('maintenance_requirement',
    sa.Column('maintenance_plan_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('target_type', sa.Enum('VESSEL', 'TECHNICAL_COMPONENT', name='maintenancetargettype', native_enum=False, length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'INSPECTION', 'CONDITION_BASED', 'RESTORATION', name='maintenancetype', native_enum=False, length=40), nullable=False),
    sa.Column('interval_type', sa.Enum('CALENDAR_DAYS', 'CALENDAR_MONTHS', 'CALENDAR_YEARS', 'RUNNING_HOURS', name='maintenanceintervaltype', native_enum=False, length=40), nullable=False),
    sa.Column('interval_value', sa.Integer(), nullable=False),
    sa.Column('due_basis', sa.Enum('CALENDAR_DATE', 'RUNNING_HOURS', name='maintenanceduebasis', native_enum=False, length=30), nullable=False),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('last_completed_running_hours', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('next_due_running_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='maintenancerequirementstatus', native_enum=False, length=20), nullable=False),
    sa.Column('instructions', sa.String(length=4000), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_plan_id'], ['maintenance_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_requirement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_requirement_maintenance_plan_id'), ['maintenance_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requirement_target_id'), ['target_id'], unique=False)

    op.create_table('member',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('member_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'TERMINATED', name='memberstatus', native_enum=False, length=20), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_member_number'), ['member_number'], unique=True)

    op.create_table('project_activity',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('activity_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='projectpriority', native_enum=False, length=20), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_finish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'activity_order', name='uq_project_activity_order')
    )
    with op.batch_alter_table('project_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_activity_project_id'), ['project_id'], unique=False)

    op.create_table('project_assignment',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('assigned_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_assignment_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_assignment_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_assignment_project_id'), ['project_id'], unique=False)

    op.create_table('project_milestone',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sequence', name='uq_project_milestone_sequence')
    )
    with op.batch_alter_table('project_milestone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_milestone_project_id'), ['project_id'], unique=False)

    op.create_table('project_reference',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('reference_order', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.Enum('ASSET', 'ORGANISATION', 'CONTACT', 'PURCHASE_ORDER', 'INVENTORY_ITEM', 'MAINTENANCE_WORK_ORDER', 'DOCUMENT', 'CERTIFICATE', name='referencetype', native_enum=False, length=40), nullable=False),
    sa.Column('external_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('reference_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'reference_order', name='uq_project_reference_order')
    )
    with op.batch_alter_table('project_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_reference_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reference_project_id'), ['project_id'], unique=False)

    op.create_table('purchase_order_line',
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.Column('description_snapshot', sa.String(length=1000), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('unit_price_amount', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('unit_price_currency', sa.Enum('DKK', 'EUR', 'USD', 'GBP', 'NOK', 'SEK', name='currency', native_enum=False, length=10), nullable=False),
    sa.Column('inventory_item_reference', sa.String(length=255), nullable=True),
    sa.Column('expected_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('line_note', sa.String(length=2000), nullable=True),
    sa.Column('received_quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'line_order', name='uq_purchase_order_line_order')
    )
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_line_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('purchase_receipt',
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_order', sa.Integer(), nullable=False),
    sa.Column('receipt_reference', sa.String(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'receipt_order', name='uq_purchase_receipt_order')
    )
    with op.batch_alter_table('purchase_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_receipt_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('role',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.Enum('BOARD', 'COMMITTEE', 'VOLUNTEER', 'OPERATIONAL', 'ADMINISTRATIVE', name='roletype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='rolestatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_role_code'), ['role_code'], unique=True)

    op.create_table('technical_component',
    sa.Column('technical_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('component_type', sa.Enum('PROPULSION_ENGINE', 'AUXILIARY_ENGINE', 'GEARBOX', 'SHAFT', 'PROPELLER', 'GENERATOR', 'PUMP', 'STEERING_GEAR', 'TANK', 'OTHER', name='technicalcomponenttype', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('installed_date', sa.Date(), nullable=True),
    sa.Column('removed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'INSTALLED', 'REMOVED', 'RETIRED', name='technicalcomponentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('specification_schema_key', sa.String(length=100), nullable=False),
    sa.Column('specification_entries', sa.JSON(), nullable=False),
    sa.Column('replacement_successor_component_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['replacement_successor_component_id'], ['technical_component.id'], ),
    sa.ForeignKeyConstraint(['technical_configuration_id'], ['technical_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technical_component', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_component_replacement_successor_component_id'), ['replacement_successor_component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_component_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_component_technical_configuration_id'), ['technical_configuration_id'], unique=False)

    op.create_table('vessel',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('registration', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shipyard', sa.String(length=255), nullable=False),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('construction_material', sa.Enum('STEEL', 'ALUMINUM', 'WOOD', 'FIBERGLASS', 'COMPOSITE', 'OTHER', name='vesselmaterial', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LAID_UP', 'RESTORATION', 'RETIRED', name='vesselstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vessel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vessel_asset_id'), ['asset_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vessel_registration'), ['registration'], unique=True)

    op.create_table('board_member',
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('appointed_on', sa.Date(), nullable=False),
    sa.Column('resigned_on', sa.Date(), nullable=True),
    sa.Column('is_chair', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_member_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_member_member_id'), ['member_id'], unique=False)

    op.create_table('committee_member',
    sa.Column('committee_id', sa.Uuid(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('function_title', sa.String(length=255), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('left_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('committee_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_committee_member_committee_id'), ['committee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_member_reference_id'), ['reference_id'], unique=False)

    op.create_table('journal_entry',
    sa.Column('journal_id', sa.Uuid(), nullable=False),
    sa.Column('entry_order', sa.Integer(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'REVERSED', name='journalentrystatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'entry_order', name='uq_journal_entry_order')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_journal_id'), ['journal_id'], unique=False)

    op.create_table('membership',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('membership_type_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ENDED', 'EXPIRED', name='membershipstatus', native_enum=False, length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['membership_type_id'], ['membership_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_membership_type_id'), ['membership_type_id'], unique=False)

    op.create_table('purchase_receipt_line',
    sa.Column('purchase_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_line_order', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], ),
    sa.ForeignKeyConstraint(['purchase_receipt_id'], ['purchase_receipt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_receipt_id', 'receipt_line_order', name='uq_purchase_receipt_line_order')
    )
    with op.batch_alter_table('purchase_receipt_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_receipt_line_purchase_order_line_id'), ['purchase_order_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_receipt_line_purchase_receipt_id'), ['purchase_receipt_id'], unique=False)

    op.create_table('role_assignment',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_assignment_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_assignment_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_assignment_role_id'), ['role_id'], unique=False)

    op.create_table('technical_component_link',
    sa.Column('technical_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('upstream_component_id', sa.Uuid(), nullable=False),
    sa.Column('downstream_component_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('DRIVES', 'COUPLED_TO', 'FEEDS', 'CONTROLS', 'CONNECTS_TO', name='componentlinkrole', native_enum=False, length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['downstream_component_id'], ['technical_component.id'], ),
    sa.ForeignKeyConstraint(['technical_configuration_id'], ['technical_configuration.id'], ),
    sa.ForeignKeyConstraint(['upstream_component_id'], ['technical_component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technical_component_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_component_link_downstream_component_id'), ['downstream_component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_component_link_technical_configuration_id'), ['technical_configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_component_link_upstream_component_id'), ['upstream_component_id'], unique=False)

    op.create_table('technical_component_replacement',
    sa.Column('technical_configuration_id', sa.Uuid(), nullable=False),
    sa.Column('replaced_component_id', sa.Uuid(), nullable=False),
    sa.Column('replacement_component_id', sa.Uuid(), nullable=False),
    sa.Column('replaced_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['replaced_component_id'], ['technical_component.id'], ),
    sa.ForeignKeyConstraint(['replacement_component_id'], ['technical_component.id'], ),
    sa.ForeignKeyConstraint(['technical_configuration_id'], ['technical_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technical_component_replacement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_component_replacement_replaced_component_id'), ['replaced_component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_component_replacement_replacement_component_id'), ['replacement_component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technical_component_replacement_technical_configuration_id'), ['technical_configuration_id'], unique=False)

    op.create_table('vessel_dimensions',
    sa.Column('vessel_id', sa.Uuid(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('beam', sa.Float(), nullable=False),
    sa.Column('draft', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vessel_dimensions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vessel_dimensions_vessel_id'), ['vessel_id'], unique=True)

    op.create_table('volunteer',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RETIRED', name='volunteerstatus', native_enum=False, length=20), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('left_at', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('max_hours_per_week', sa.Integer(), nullable=False),
    sa.Column('preferred_days', sa.String(length=1000), nullable=False),
    sa.Column('skills', sa.String(length=2000), nullable=False),
    sa.Column('certificates', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteer_member_id'), ['member_id'], unique=False)

    op.create_table('journal_line',
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('DEBIT', 'CREDIT', name='postingside', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('DKK', 'EUR', 'USD', 'GBP', 'NOK', 'SEK', name='currency', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_entry_id', 'line_order', name='uq_journal_line_order')
    )
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_line_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_journal_entry_id'), ['journal_entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_line_journal_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_account_id'))

    op.drop_table('journal_line')
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_member_id'))
        batch_op.drop_index(batch_op.f('ix_volunteer_contact_id'))

    op.drop_table('volunteer')
    with op.batch_alter_table('vessel_dimensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vessel_dimensions_vessel_id'))

    op.drop_table('vessel_dimensions')
    with op.batch_alter_table('technical_component_replacement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_component_replacement_technical_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_technical_component_replacement_replacement_component_id'))
        batch_op.drop_index(batch_op.f('ix_technical_component_replacement_replaced_component_id'))

    op.drop_table('technical_component_replacement')
    with op.batch_alter_table('technical_component_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_component_link_upstream_component_id'))
        batch_op.drop_index(batch_op.f('ix_technical_component_link_technical_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_technical_component_link_downstream_component_id'))

    op.drop_table('technical_component_link')
    with op.batch_alter_table('role_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_assignment_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_assignment_organization_id'))
        batch_op.drop_index(batch_op.f('ix_role_assignment_assignee_id'))

    op.drop_table('role_assignment')
    with op.batch_alter_table('purchase_receipt_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_receipt_line_purchase_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_receipt_line_purchase_order_line_id'))

    op.drop_table('purchase_receipt_line')
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_membership_type_id'))
        batch_op.drop_index(batch_op.f('ix_membership_member_id'))

    op.drop_table('membership')
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_journal_id'))

    op.drop_table('journal_entry')
    with op.batch_alter_table('committee_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committee_member_reference_id'))
        batch_op.drop_index(batch_op.f('ix_committee_member_committee_id'))

    op.drop_table('committee_member')
    with op.batch_alter_table('board_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_member_member_id'))
        batch_op.drop_index(batch_op.f('ix_board_member_board_id'))

    op.drop_table('board_member')
    with op.batch_alter_table('vessel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vessel_registration'))
        batch_op.drop_index(batch_op.f('ix_vessel_asset_id'))

    op.drop_table('vessel')
    with op.batch_alter_table('technical_component', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_component_technical_configuration_id'))
        batch_op.drop_index(batch_op.f('ix_technical_component_serial_number'))
        batch_op.drop_index(batch_op.f('ix_technical_component_replacement_successor_component_id'))

    op.drop_table('technical_component')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_role_code'))
        batch_op.drop_index(batch_op.f('ix_role_organization_id'))

    op.drop_table('role')
    with op.batch_alter_table('purchase_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_receipt_purchase_order_id'))

    op.drop_table('purchase_receipt')
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_purchase_order_id'))

    op.drop_table('purchase_order_line')
    with op.batch_alter_table('project_reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_reference_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_reference_external_id'))

    op.drop_table('project_reference')
    with op.batch_alter_table('project_milestone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_milestone_project_id'))

    op.drop_table('project_milestone')
    with op.batch_alter_table('project_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_assignment_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_assignment_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_project_assignment_contact_id'))

    op.drop_table('project_assignment')
    with op.batch_alter_table('project_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_activity_project_id'))

    op.drop_table('project_activity')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_member_number'))
        batch_op.drop_index(batch_op.f('ix_member_contact_id'))

    op.drop_table('member')
    with op.batch_alter_table('maintenance_requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_requirement_target_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requirement_maintenance_plan_id'))

    op.drop_table('maintenance_requirement')
    with op.batch_alter_table('maintenance_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_record_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_record_target_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_record_maintenance_requirement_id'))

    op.drop_table('maintenance_record')
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_posting_date'))
        batch_op.drop_index(batch_op.f('ix_journal_journal_number'))
        batch_op.drop_index(batch_op.f('ix_journal_fiscal_year_id'))

    op.drop_table('journal')
    with op.batch_alter_table('inventory_stock_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_stock_position_vessel_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_stock_position_location_key'))
        batch_op.drop_index(batch_op.f('ix_inventory_stock_position_inventory_item_id'))

    op.drop_table('inventory_stock_position')
    with op.batch_alter_table('inventory_stock_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_stock_movement_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_stock_movement_movement_order'))
        batch_op.drop_index(batch_op.f('ix_inventory_stock_movement_inventory_item_id'))

    op.drop_table('inventory_stock_movement')
    with op.batch_alter_table('fiscal_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_period_fiscal_year_id'))

    op.drop_table('fiscal_period')
    with op.batch_alter_table('document_reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_reference_target_capability'))
        batch_op.drop_index(batch_op.f('ix_document_reference_target_aggregate_id'))
        batch_op.drop_index(batch_op.f('ix_document_reference_document_id'))

    op.drop_table('document_reference')
    with op.batch_alter_table('contingent_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contingent_plan_membership_type_id'))

    op.drop_table('contingent_plan')
    with op.batch_alter_table('contact_phone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_phone_number'))
        batch_op.drop_index(batch_op.f('ix_contact_phone_contact_id'))

    op.drop_table('contact_phone')
    op.drop_table('contact_person')
    op.drop_table('contact_organisation')
    with op.batch_alter_table('contact_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_email_contact_id'))
        batch_op.drop_index(batch_op.f('ix_contact_email_address'))

    op.drop_table('contact_email')
    with op.batch_alter_table('contact_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_address_contact_id'))

    op.drop_table('contact_address')
    with op.batch_alter_table('committee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committee_organization_id'))

    op.drop_table('committee')
    with op.batch_alter_table('certificate_compliance_observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_compliance_observation_certificate_id'))

    op.drop_table('certificate_compliance_observation')
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_organization_id'))

    op.drop_table('board')
    with op.batch_alter_table('asset_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_location_asset_id'))

    op.drop_table('asset_location')
    op.drop_table('CONTACT_RELATION')
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_target_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_maintenance_requirement_id'))

    op.drop_table('work_order')
    with op.batch_alter_table('voyage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voyage_voyage_reference'))
        batch_op.drop_index(batch_op.f('ix_voyage_vessel_id'))

    op.drop_table('voyage')
    with op.batch_alter_table('technical_configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_configuration_vessel_id'))

    op.drop_table('technical_configuration')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_supplier_reference'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_purchase_order_number'))

    op.drop_table('purchase_order')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_project_number'))

    op.drop_table('project')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_organization_number'))

    op.drop_table('organization')
    with op.batch_alter_table('membership_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_type_code'))

    op.drop_table('membership_type')
    with op.batch_alter_table('maintenance_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_plan_target_id'))

    op.drop_table('maintenance_plan')
    with op.batch_alter_table('ledger_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_account_account_number'))

    op.drop_table('ledger_account')
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_item_item_reference'))

    op.drop_table('inventory_item')
    with op.batch_alter_table('fiscal_year', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_year_year'))

    op.drop_table('fiscal_year')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_document_type'))
        batch_op.drop_index(batch_op.f('ix_document_document_number'))

    op.drop_table('document')
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_contact_number'))

    op.drop_table('contact')
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_target_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_renewed_from_certificate_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_certificate_type_id'))

    op.drop_table('certificate')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_owner_id'))
        batch_op.drop_index(batch_op.f('ix_asset_asset_number'))

    op.drop_table('asset')
    # ### end Alembic commands ###
